<!-- capture tab -->
<div class="tab-pane fade" id="capture">
  <h4 class="mt-3 mb-3"><?php echo _("Capture files") ;?></h4>
  <p><?php echo _("Capture files generated by <code>tshark</code> are displayed below."); ?></p>
  <div class="row">
    <div class="mb-3 col-md-8 mt-2">

      <?php if (empty($__template_data['captureFiles'])): ?>
        <div class="alert alert-info">
          <i class="fas fa-info-circle"></i> <?php echo _("No capture files found in /tmp directory"); ?>
        </div>
      <?php else: ?>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th><?php echo _("Filename"); ?></th>
                <th><?php echo _("Size"); ?></th>
                <th><?php echo _("Modified"); ?></th>
                <th><?php echo _("Actions"); ?></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($__template_data['captureFiles'] as $file): ?>
                <tr>
                  <td>
                    <i class="fa-regular fa-file-code"></i>
                    <code><?php echo htmlspecialchars($file['name'], ENT_QUOTES); ?></code>
                  </td>
                  <td><?php echo htmlspecialchars($file['size_human'], ENT_QUOTES); ?></td>
                  <td>
                    <small><?php echo htmlspecialchars($file['modified_human'], ENT_QUOTES); ?></small>
                  </td>
                  <td class="text-nowrap">

                    <a href="?download=<?php echo urlencode($file['name']); ?>&token=<?php echo htmlspecialchars($file['download_token'], ENT_QUOTES); ?>" 
                       class="btn btn-sm btn-outline-success" 
                       title="<?php echo _("Download file"); ?>">
                      <i class="fas fa-download"></i>
                    </a>

                    <button type="button" 
                        class="btn btn-sm btn-outline-danger" 
                        data-bs-toggle="modal" 
                        data-bs-target="#deleteModal"
                        data-filename="<?php echo htmlspecialchars($file['name'], ENT_QUOTES); ?>"
                        title="<?php echo _("Delete file"); ?>">
                        <i class="fa fa-trash-alt"></i>
                    </button> 

                  </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>
        </div>

        <div class="mt-3">
          <small class="text-muted">
            <i class="fas fa-info-circle"></i> 
            <?php 
            $totalFiles = count($__template_data['captureFiles']);
            $totalSize = array_sum(array_column($__template_data['captureFiles'], 'size'));
            printf(_("Total: %d file(s), %s"), $totalFiles, getHumanReadableDatasize($totalSize)); 
            ?>
          </small>
        </div>
      <?php endif; ?>

    </div>
  </div>
</div><!-- /.tab-pane -->

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-title" id="deleteModalLabel">
          <i class="fas fa-exclamation-triangle"></i> <?php echo _("Confirm deletion"); ?>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p><?php echo _("Are you sure you want to delete this file?"); ?></p>
        <p class="mb-0"><strong><code id="deleteFileName"></code></strong></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><?php echo _("Cancel"); ?></button>
        <button type="button" class="btn btn-danger" onclick="document.getElementById('deleteForm').submit();">
          <i class="fa fa-trash-alt"></i> <?php echo _("Delete"); ?>
        </button>
      </div>
    </div>
  </div>
</div>

<script>
// handle delete modal
document.addEventListener('DOMContentLoaded', function() {
  var deleteModal = document.getElementById('deleteModal');
  if (deleteModal) {
    deleteModal.addEventListener('show.bs.modal', function(event) {
      var button = event.relatedTarget;
      var filename = button.getAttribute('data-filename');

      document.getElementById('deleteFileName').textContent = filename;
      document.getElementById('deleteFileInput').value = filename;
    });
  }
});
</script>

