[Unit]
After=
After=network-online.target switchberry-apply-timing.service switchberry-full-init.service
Wants=network-online.target
Requires=switchberry-apply-timing.service

[Service]
ExecStart=
ExecStart=/usr/local/sbin/raspap-switchberryctl _role-apply
